sudo: false
language: java

before_script:
  - psql -U postgres -c "create user test with password 'test';"
  - psql -c 'create database test owner test;' -U postgres
  - echo "MAVEN_OPTS='-Xmx1g'" > ~/.mavenrc

env:
  global:
    - secure: "2Y1byuAHollEQCOKjEfairV2AQoeXXThscmY+q1AtQTDl87ujlTbqAAn4Ou1wIkXR+EwmJceV5j+svH9m0YYrMRDMxPgSoEsIAcCREwK0IJ4lI0a8Rgox4JTDZPQ0bN1jTCNNieyWwz18n7G8NsEBMfrpl1rS5lv7KWTg9ddjq4="
    - secure: "6qt9AryWWe97s4B5ZbPn64lfKsRrEjCQV/bBbjA35FTwjDSLjZYrcDQ8YmPPHvzdp8AiZlL5BdM1C3V+PC/mcFFiKfJEHm9JcQRgN5s8LZrHy8RX58HHBKWSb1Z3govlniZXiz7vYNxHLT5GC1VouzI0z3PSOpXP22qcMWlSGUc="

script:
  # make sure previous build artifacts are not used for subsequent builds
  - rm -rf $HOME/.m2/repository/org/postgresql || true
  - export JDK6_HOME=$(jdk_switcher home openjdk6)
  - export JDK7_HOME=$(jdk_switcher home openjdk7)
  - export JDK8_HOME=$(jdk_switcher home oraclejdk8)
  - envsubst < toolchains.xml > ~/.m2/toolchains.xml
  - ./travis_build.sh
  # To avoid useless S3 cache updates (https://github.com/travis-ci/travis-ci/issues/1441#issuecomment-67607074)
  #- mkdir /tmp/cache-trick
  #- mv $HOME/.m2/repository/org/postgresql /tmp/cache-trick/

before_cache:
  # No sense in caching current build artifacts
  rm -rf $HOME/.m2/repository/org/postgresql

# Skip default "mvn install" issued by Travis
# Root project cannot be compiled with older JDKs, so it makes sense to just skip the step
install: true

cache:
  directories:
    - '$HOME/.m2/repository'

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      addons:
        postgresql: "9.4"
      env: PG_VERSION=9.4
    - jdk: openjdk7
      addons:
        postgresql: "9.4"
      env: PG_VERSION=9.4
    - jdk: openjdk6
      addons:
        postgresql: "9.4"
      env: PG_VERSION=9.4
    - jdk: oraclejdk8
      addons:
        postgresql: "9.3"
      env: PG_VERSION=9.3
    - jdk: openjdk7
      addons:
        postgresql: "9.3"
      env: PG_VERSION=9.3
    - jdk: openjdk6
      addons:
        postgresql: "9.3"
      env: PG_VERSION=9.3
    - jdk: oraclejdk8
      addons:
        postgresql: "9.2"
      env: PG_VERSION=9.2
    - jdk: openjdk7
      addons:
        postgresql: "9.2"
      env: PG_VERSION=9.2
    - jdk: openjdk6
      addons:
        postgresql: "9.2"
      env: PG_VERSION=9.2
    - jdk: oraclejdk8
      addons:
        postgresql: "9.1"
      env: PG_VERSION=9.1
    - jdk: openjdk7
      addons:
        postgresql: "9.1"
      env: PG_VERSION=9.1
    - jdk: openjdk6
      addons:
        postgresql: "9.1"
      env: PG_VERSION=9.1

# Deploy snapshots to Maven Central
after_success:
  - "test $TRAVIS_PULL_REQUEST == 'false' && test $TRAVIS_BRANCH == 'master' && test $PG_VERSION == '9.4' && ./travis_deploy.sh"
